language: node_js

node_js:
  - '12'

cache:
  directories:
    - node_modules

script:
  - npm run build
  - npm run test
  - npm run lint

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  on:
    branch: master
